
/**
 * A rough property set for every entity delegate generated by Prisma.
 */
export type PrismaDelegate = {
    findMany(arg: Record<string, any>): any,
    findUnique(arg: Record<string, any>): any,
    create(arg: Record<string, any>): any,
    upsert(arg: Record<string, any>): any,
    update(arg: Record<string, any>): any,
    delete(arg: Record<string, any>): any,
    aggregate(arg: Record<string, any>): any,
    count(arg: Record<string, any>): any
};
