version: “3”
services:
  zap-node:
    image: owasp/zap2docker-stable:2.10.0
    command: zap-api-scan.py -t http://host.docker.internal:3000/openapi.yml -f openapi -r node-webservice-report.html
    volumes:
      - ./report:/zap/wrk:rw
# If running a Linux host
#      - /etc/timezone:/etc/timezone:ro
#      - /etc/localtime:/etc/localtime:ro